/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package soundengine.ui;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import soundengine.OpenALFacade;

/**
 *
 * @author soote
 */
public class Demo extends javax.swing.JFrame {

    private String fileName;
    private int[] sources = new int[3];
    private int[] buffers = new int[3];

    private OpenALFacade openAL = new OpenALFacade();

    /**
     * Creates new form Demo2
     */
    public Demo() {
        lookAndFeel();
        initComponents();
        initFileChooser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        playSample = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        userSampleInput = new javax.swing.JTextField();
        stopSample = new javax.swing.JButton();
        pauseSample = new javax.swing.JButton();
        sampleSelect = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        playSample1 = new javax.swing.JButton();
        sampleSelect1 = new javax.swing.JButton();
        pauseSample1 = new javax.swing.JButton();
        stopSample1 = new javax.swing.JButton();
        userSampleInput1 = new javax.swing.JTextField();
        stopSample2 = new javax.swing.JButton();
        userSampleInput2 = new javax.swing.JTextField();
        sampleSelect2 = new javax.swing.JButton();
        pauseSample2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        playSample2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(232, 232, 232));

        playSample.setText("Play");
        playSample.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSampleActionPerformed(evt);
            }
        });

        jLabel1.setText("Select First Sample:");

        userSampleInput.setEnabled(false);
        userSampleInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userSampleInputActionPerformed(evt);
            }
        });

        stopSample.setText("Stop");
        stopSample.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopSampleActionPerformed(evt);
            }
        });

        pauseSample.setText("Pause");
        pauseSample.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseSampleActionPerformed(evt);
            }
        });

        sampleSelect.setText("...");
        sampleSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sampleSelectActionPerformed(evt);
            }
        });

        jLabel2.setText("Select Second Sample:");

        playSample1.setText("Play");
        playSample1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSample1ActionPerformed(evt);
            }
        });

        sampleSelect1.setText("...");
        sampleSelect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sampleSelect1ActionPerformed(evt);
            }
        });

        pauseSample1.setText("Pause");
        pauseSample1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseSample1ActionPerformed(evt);
            }
        });

        stopSample1.setText("Stop");
        stopSample1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopSample1ActionPerformed(evt);
            }
        });

        userSampleInput1.setEnabled(false);
        userSampleInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userSampleInput1ActionPerformed(evt);
            }
        });

        stopSample2.setText("Stop");
        stopSample2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopSample2ActionPerformed(evt);
            }
        });

        userSampleInput2.setEnabled(false);
        userSampleInput2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userSampleInput2ActionPerformed(evt);
            }
        });

        sampleSelect2.setText("...");
        sampleSelect2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sampleSelect2ActionPerformed(evt);
            }
        });

        pauseSample2.setText("Pause");
        pauseSample2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseSample2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Select Third Sample:");

        playSample2.setText("Play");
        playSample2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSample2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel4.setText("press e to quit");

        jMenu1.setText("File");

        exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, 0));
        exit.setText("Exit");
        exit.setToolTipText("");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu1.add(exit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(playSample1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(pauseSample1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(stopSample1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(userSampleInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(sampleSelect1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(playSample2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(pauseSample2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(stopSample2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(userSampleInput2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(sampleSelect2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(playSample, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(pauseSample, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(stopSample, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(userSampleInput, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(sampleSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userSampleInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sampleSelect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playSample)
                    .addComponent(pauseSample)
                    .addComponent(stopSample))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userSampleInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sampleSelect1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playSample1)
                    .addComponent(pauseSample1)
                    .addComponent(stopSample1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userSampleInput2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sampleSelect2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playSample2)
                    .addComponent(pauseSample2)
                    .addComponent(stopSample2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playSampleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playSampleActionPerformed
        openAL.playSound(sources[0]);
    }//GEN-LAST:event_playSampleActionPerformed

    private void stopSampleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopSampleActionPerformed
        openAL.stopSound(sources[0]);
    }//GEN-LAST:event_stopSampleActionPerformed

    private void pauseSampleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseSampleActionPerformed
        openAL.pauseSound(sources[0]);
    }//GEN-LAST:event_pauseSampleActionPerformed

    private void sampleSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sampleSelectActionPerformed
        selectSample(0, userSampleInput);
    }//GEN-LAST:event_sampleSelectActionPerformed

    private void selectSample(int index, JTextField input) {
        fileChooser
                .setCurrentDirectory(new File(
                                System.getProperty("user.dir") + "/src/music"));
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            fileName = file.getName();
            System.out.println(fileName);
            input.setText(file.getAbsolutePath());

            buffers[index] = openAL.loadSample(fileName);
            sources[index] = openAL.storeSource(buffers[index]);
            openAL.storeListener();
        } else {
            System.out.println("NOTHING SELECTED");
        }
    }

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        openAL.cleanUp(sources[0], buffers[0]);
        openAL.cleanUp(sources[0], buffers[0]);
        openAL.cleanUp(sources[0], buffers[0]);
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void userSampleInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userSampleInputActionPerformed
    }//GEN-LAST:event_userSampleInputActionPerformed

    private void playSample1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playSample1ActionPerformed
        openAL.playSound(sources[1]);
    }//GEN-LAST:event_playSample1ActionPerformed

    private void sampleSelect1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sampleSelect1ActionPerformed
        selectSample(1, userSampleInput1);
    }//GEN-LAST:event_sampleSelect1ActionPerformed

    private void pauseSample1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseSample1ActionPerformed
        openAL.pauseSound(sources[1]);
    }//GEN-LAST:event_pauseSample1ActionPerformed

    private void stopSample1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopSample1ActionPerformed
        openAL.stopSound(sources[1]);
    }//GEN-LAST:event_stopSample1ActionPerformed

    private void userSampleInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userSampleInput1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userSampleInput1ActionPerformed

    private void stopSample2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopSample2ActionPerformed
        openAL.stopSound(sources[2]);
    }//GEN-LAST:event_stopSample2ActionPerformed

    private void userSampleInput2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userSampleInput2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userSampleInput2ActionPerformed

    private void sampleSelect2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sampleSelect2ActionPerformed
        selectSample(2, userSampleInput2);
    }//GEN-LAST:event_sampleSelect2ActionPerformed

    private void pauseSample2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseSample2ActionPerformed
        openAL.pauseSound(sources[2]);
    }//GEN-LAST:event_pauseSample2ActionPerformed

    private void playSample2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playSample2ActionPerformed
        openAL.playSound(sources[2]);
    }//GEN-LAST:event_playSample2ActionPerformed
    private void initFileChooser() {
        FileNameExtensionFilter filter = new FileNameExtensionFilter("WAV audio",
                "wav");
        fileChooser.setFileFilter(filter);

    }
    private void lookAndFeel() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                    .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem exit;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton pauseSample;
    private javax.swing.JButton pauseSample1;
    private javax.swing.JButton pauseSample2;
    private javax.swing.JButton playSample;
    private javax.swing.JButton playSample1;
    private javax.swing.JButton playSample2;
    private javax.swing.JButton sampleSelect;
    private javax.swing.JButton sampleSelect1;
    private javax.swing.JButton sampleSelect2;
    private javax.swing.JButton stopSample;
    private javax.swing.JButton stopSample1;
    private javax.swing.JButton stopSample2;
    private javax.swing.JTextField userSampleInput;
    private javax.swing.JTextField userSampleInput1;
    private javax.swing.JTextField userSampleInput2;
    // End of variables declaration//GEN-END:variables

}
