package soundengine.ui;

import java.io.File;
import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import soundengine.Buffer;
import soundengine.OpenALFacade;
import soundengine.Source;

public class Demo extends javax.swing.JFrame {

    DefaultListModel bufferListModel;
    DefaultListModel sourceListModel;
    private static OpenALFacade openAL = new OpenALFacade();
    private LinkedList<Buffer> buffers = new LinkedList<>();
    private LinkedList<Source> sources = new LinkedList<>();
    /**
     * Creates new form Demo2
     */
    public Demo() {
        lookAndFeel();
        //Set listener location
        openAL.newListener();
        buffers.add(new Buffer("Battle.wav"));
        buffers.add(new Buffer("Footsteps.wav"));
        buffers.add(new Buffer("Gun2.wav"));
        initLists();
        initComponents();
        initFileChooser();
    }

    private void initFileChooser() {
        FileNameExtensionFilter filter = new FileNameExtensionFilter("WAV audio",
                "wav");
        fileChooser.setFileFilter(filter);
    }

    private void initLists() {
        bufferListModel = new DefaultListModel();
        sourceListModel = new DefaultListModel();

        for (Buffer s : buffers) {
            bufferListModel.addElement(s.name);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        listenerVelocityInput = new javax.swing.JTextField();
        listenerPositionInput = new javax.swing.JTextField();
        setVelocityBut = new javax.swing.JButton();
        setPositionBut = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        moveListener5But = new javax.swing.JButton();
        moveListener1But = new javax.swing.JButton();
        moveListener3But = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bufferList = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sourceList = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        isLoopingCB = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jSlider2 = new javax.swing.JSlider();
        stopSample1 = new javax.swing.JButton();
        pauseSample1 = new javax.swing.JButton();
        playSample1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        deleteSrcBut = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        soucePositionInput = new javax.swing.JTextField();
        sourceVelocityInput = new javax.swing.JTextField();
        setVelocityBut1 = new javax.swing.JButton();
        setPositionBut1 = new javax.swing.JButton();
        moveSource1But = new javax.swing.JButton();
        moveSource3But = new javax.swing.JButton();
        moveSource5But = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        fadeInBut = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        stopSample10 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        pitchSlider = new javax.swing.JSlider();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        loadSourceButton = new javax.swing.JButton();
        loadBufferButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(7, 54, 66));
        setMinimumSize(new java.awt.Dimension(640, 275));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                cleanUp(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(238, 232, 213));

        jPanel1.setBackground(new java.awt.Color(7, 54, 66));

        jLabel2.setForeground(new java.awt.Color(101, 123, 131));
        jLabel2.setText("Velocity:");

        jLabel1.setForeground(new java.awt.Color(101, 123, 131));
        jLabel1.setText("Position:");

        listenerVelocityInput.setText("0 0 0");

        listenerPositionInput.setText("0 0 0");

        setVelocityBut.setBackground(new java.awt.Color(220, 50, 47));
        setVelocityBut.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        setVelocityBut.setForeground(new java.awt.Color(238, 232, 213));
        setVelocityBut.setText("Set");
        setVelocityBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setVelocityButActionPerformed(evt);
            }
        });

        setPositionBut.setBackground(new java.awt.Color(220, 50, 47));
        setPositionBut.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        setPositionBut.setForeground(new java.awt.Color(238, 232, 213));
        setPositionBut.setText("Set");
        setPositionBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setPositionButActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(147, 161, 161));
        jLabel4.setText("Listener Params:");

        moveListener5But.setBackground(new java.awt.Color(220, 50, 47));
        moveListener5But.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        moveListener5But.setForeground(new java.awt.Color(238, 232, 213));
        moveListener5But.setText("Move 5 sec");
        moveListener5But.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveListener5ButActionPerformed(evt);
            }
        });

        moveListener1But.setBackground(new java.awt.Color(220, 50, 47));
        moveListener1But.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        moveListener1But.setForeground(new java.awt.Color(238, 232, 213));
        moveListener1But.setText("Move 1 sec");
        moveListener1But.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveListener1ButActionPerformed(evt);
            }
        });

        moveListener3But.setBackground(new java.awt.Color(220, 50, 47));
        moveListener3But.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        moveListener3But.setForeground(new java.awt.Color(238, 232, 213));
        moveListener3But.setText("Move 3 sec");
        moveListener3But.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveListener3ButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(listenerVelocityInput, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(listenerPositionInput, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(setVelocityBut)
                            .addComponent(setPositionBut)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(moveListener1But)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moveListener3But)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(moveListener5But)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setPositionBut)
                    .addComponent(listenerPositionInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setVelocityBut)
                    .addComponent(listenerVelocityInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moveListener1But)
                    .addComponent(moveListener3But)
                    .addComponent(moveListener5But))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        bufferList.setBackground(new java.awt.Color(0, 43, 54));
        bufferList.setForeground(new java.awt.Color(203, 75, 22));
        bufferList.setModel(bufferListModel);
        jScrollPane1.setViewportView(bufferList);

        jLabel6.setForeground(new java.awt.Color(88, 110, 117));
        jLabel6.setText("Buffers");

        sourceList.setBackground(new java.awt.Color(0, 43, 54));
        sourceList.setForeground(new java.awt.Color(181, 137, 0));
        sourceList.setModel(sourceListModel);
        jScrollPane2.setViewportView(sourceList);

        jLabel5.setForeground(new java.awt.Color(88, 110, 117));
        jLabel5.setText("Sources:");

        jPanel2.setBackground(new java.awt.Color(7, 54, 66));

        isLoopingCB.setBackground(new java.awt.Color(7, 54, 66));
        isLoopingCB.setForeground(new java.awt.Color(203, 75, 22));
        isLoopingCB.setSelected(true);
        isLoopingCB.setText("Looping");
        isLoopingCB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                isLoopingCBMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(203, 75, 22));
        jLabel7.setText("Volume:");

        jSlider2.setBackground(new java.awt.Color(7, 54, 66));
        jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider2StateChanged(evt);
            }
        });

        stopSample1.setBackground(new java.awt.Color(220, 50, 47));
        stopSample1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        stopSample1.setForeground(new java.awt.Color(238, 232, 213));
        stopSample1.setText("Stop");
        stopSample1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopSample1ActionPerformed(evt);
            }
        });

        pauseSample1.setBackground(new java.awt.Color(203, 75, 22));
        pauseSample1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        pauseSample1.setForeground(new java.awt.Color(238, 232, 213));
        pauseSample1.setText("Pause");
        pauseSample1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseSample1ActionPerformed(evt);
            }
        });

        playSample1.setBackground(new java.awt.Color(133, 153, 0));
        playSample1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        playSample1.setForeground(new java.awt.Color(238, 232, 213));
        playSample1.setText("Play");
        playSample1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playSample1ActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(147, 161, 161));
        jLabel8.setText("Source Params:");

        deleteSrcBut.setBackground(new java.awt.Color(220, 50, 47));
        deleteSrcBut.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        deleteSrcBut.setForeground(new java.awt.Color(253, 246, 227));
        deleteSrcBut.setText("Delete Source");
        deleteSrcBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSrcButActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(238, 232, 213));

        jLabel9.setForeground(new java.awt.Color(101, 123, 131));
        jLabel9.setText("Position:");

        jLabel10.setForeground(new java.awt.Color(101, 123, 131));
        jLabel10.setText("Velocity:");

        soucePositionInput.setText("0 0 0");

        sourceVelocityInput.setText("0 0 0");

        setVelocityBut1.setBackground(new java.awt.Color(220, 50, 47));
        setVelocityBut1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        setVelocityBut1.setForeground(new java.awt.Color(238, 232, 213));
        setVelocityBut1.setText("Set");
        setVelocityBut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setVelocityBut1ActionPerformed(evt);
            }
        });

        setPositionBut1.setBackground(new java.awt.Color(220, 50, 47));
        setPositionBut1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        setPositionBut1.setForeground(new java.awt.Color(238, 232, 213));
        setPositionBut1.setText("Set");
        setPositionBut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setPositionBut1ActionPerformed(evt);
            }
        });

        moveSource1But.setBackground(new java.awt.Color(220, 50, 47));
        moveSource1But.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        moveSource1But.setForeground(new java.awt.Color(238, 232, 213));
        moveSource1But.setText("Move 1 sec");
        moveSource1But.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveSource1ButActionPerformed(evt);
            }
        });

        moveSource3But.setBackground(new java.awt.Color(220, 50, 47));
        moveSource3But.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        moveSource3But.setForeground(new java.awt.Color(238, 232, 213));
        moveSource3But.setText("Move 3 sec");
        moveSource3But.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveSource3ButActionPerformed(evt);
            }
        });

        moveSource5But.setBackground(new java.awt.Color(220, 50, 47));
        moveSource5But.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        moveSource5But.setForeground(new java.awt.Color(238, 232, 213));
        moveSource5But.setText("Move 5 sec");
        moveSource5But.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveSource5ButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sourceVelocityInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(soucePositionInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(setVelocityBut1)
                            .addComponent(setPositionBut1)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(moveSource1But)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moveSource3But)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(moveSource5But)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setPositionBut1)
                    .addComponent(soucePositionInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setVelocityBut1)
                    .addComponent(sourceVelocityInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moveSource1But)
                    .addComponent(moveSource3But)
                    .addComponent(moveSource5But))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fadeInBut.setBackground(new java.awt.Color(203, 75, 22));
        fadeInBut.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        fadeInBut.setForeground(new java.awt.Color(238, 232, 213));
        fadeInBut.setText("Fade In");
        fadeInBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fadeInButActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(147, 161, 161));
        jLabel14.setText("Effects:");

        stopSample10.setBackground(new java.awt.Color(203, 75, 22));
        stopSample10.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        stopSample10.setForeground(new java.awt.Color(238, 232, 213));
        stopSample10.setText("Fade Out");
        stopSample10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopSample10ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(203, 75, 22));
        jLabel12.setText("Pitch:");

        pitchSlider.setBackground(new java.awt.Color(7, 54, 66));
        pitchSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pitchSliderStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pitchSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel14)
                        .addComponent(jLabel12)
                        .addComponent(stopSample10, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fadeInBut, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fadeInBut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stopSample10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pitchSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(playSample1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(stopSample1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pauseSample1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(deleteSrcBut))
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isLoopingCB, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteSrcBut)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(playSample1)
                            .addComponent(pauseSample1)
                            .addComponent(stopSample1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(isLoopingCB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 204));

        jLabel13.setFont(new java.awt.Font("Droid Sans Mono", 1, 48)); // NOI18N
        jLabel13.setText("Game Engine Demo");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addContainerGap())
        );

        loadSourceButton.setBackground(new java.awt.Color(133, 153, 0));
        loadSourceButton.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        loadSourceButton.setForeground(new java.awt.Color(238, 232, 213));
        loadSourceButton.setText("Load Into Source");
        loadSourceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadSourceButtonActionPerformed(evt);
            }
        });

        loadBufferButton.setBackground(new java.awt.Color(133, 153, 0));
        loadBufferButton.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        loadBufferButton.setForeground(new java.awt.Color(238, 232, 213));
        loadBufferButton.setText("Load New Buffer");
        loadBufferButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBufferButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(loadBufferButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(loadSourceButton))
                            .addComponent(jScrollPane2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(loadBufferButton)
                    .addComponent(loadSourceButton)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        jMenu1.setText("File");

        exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, 0));
        exit.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        exit.setText("Exit");
        exit.setToolTipText("");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu1.add(exit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        //free up the openAL sources and buffers
        openAL.cleanUp(sources, buffers);
        //clear the ui
        this.dispose();
        //free the openAL environment
        OpenALFacade.destructor();
    }//GEN-LAST:event_exitActionPerformed

    private void playSample1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playSample1ActionPerformed
        //get select list index
        int srcIndex = sourceList.getSelectedIndex();
        //get sample at selected list index from linkedlist
        Source src = sources.get(srcIndex);

        openAL.playSound(src);
    }//GEN-LAST:event_playSample1ActionPerformed

    private void pauseSample1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseSample1ActionPerformed
        //get select list index
        int srcIndex = sourceList.getSelectedIndex();
        //get sample at selected list index from linkedlist
        Source src = sources.get(srcIndex);
        openAL.pauseSound(src);
    }//GEN-LAST:event_pauseSample1ActionPerformed

    private void stopSample1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopSample1ActionPerformed
        //get select list index
        int srcIndex = sourceList.getSelectedIndex();
        //get sample at selected list index from linkedlist
        Source src = sources.get(srcIndex);
        openAL.stopSound(src);
    }//GEN-LAST:event_stopSample1ActionPerformed

    private void jSlider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider2StateChanged
        //get select list index
        int srcIndex = sourceList.getSelectedIndex();
        //get sample at selected list index from linkedlist
        Source src = sources.get(srcIndex);
        openAL.setVolume(src, jSlider2.getValue());
    }//GEN-LAST:event_jSlider2StateChanged

    private void stopSample10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopSample10ActionPerformed
        //get select list index
        int srcIndex = sourceList.getSelectedIndex();
        //get sample at selected list index from linkedlist
        Source src = sources.get(srcIndex);
        openAL.fadeOutSound(src, soucePositionInput, sourceVelocityInput);
    }//GEN-LAST:event_stopSample10ActionPerformed

    private void fadeInButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fadeInButActionPerformed
        //get select list index
        int srcIndex = sourceList.getSelectedIndex();
        //get sample at selected list index from linkedlist
        Source src = sources.get(srcIndex);
        openAL.fadeInSound(src, soucePositionInput, sourceVelocityInput);
    }//GEN-LAST:event_fadeInButActionPerformed

    private void setPositionButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setPositionButActionPerformed
        String[] input = listenerPositionInput.getText().split(" ");
        openAL.setListenerPosition(Float.parseFloat(input[0]),
                Float.parseFloat(input[1]),
                Float.parseFloat(input[2]));

    }//GEN-LAST:event_setPositionButActionPerformed

    private void setVelocityButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setVelocityButActionPerformed
        String[] input = listenerVelocityInput.getText().split(" ");
        openAL.setListenerVelocity(Float.parseFloat(input[0]),
                Float.parseFloat(input[1]),
                Float.parseFloat(input[2]));
    }//GEN-LAST:event_setVelocityButActionPerformed

    private void isLoopingCBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isLoopingCBMouseClicked
        //get select list index
        int srcIndex = sourceList.getSelectedIndex();
        //get sample at selected list index from linkedlist
        Source src = sources.get(srcIndex);
        openAL.setLoopingMode(src, isLoopingCB.isSelected());
    }//GEN-LAST:event_isLoopingCBMouseClicked

    private void setVelocityBut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setVelocityBut1ActionPerformed
        //get select list index
        int srcIndex = sourceList.getSelectedIndex();
        //get sample at selected list index from linkedlist
        Source src = sources.get(srcIndex);
        String[] input = sourceVelocityInput.getText().split(" ");
        openAL.setVelocity(src, new float[] {Float.parseFloat(input[0]),
            Float.parseFloat(input[1]),
            Float.parseFloat(input[2])});
    }//GEN-LAST:event_setVelocityBut1ActionPerformed

    private void setPositionBut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setPositionBut1ActionPerformed
        //get select list index
        int srcIndex = sourceList.getSelectedIndex();
        //get sample at selected list index from linkedlist
        Source src = sources.get(srcIndex);
        String[] input = soucePositionInput.getText().split(" ");
        openAL.setPosition(src, new float[] {Float.parseFloat(input[0]),
            Float.parseFloat(input[1]),
            Float.parseFloat(input[2])});

    }//GEN-LAST:event_setPositionBut1ActionPerformed

    private void pitchSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pitchSliderStateChanged
        //selected list index == linkedlist index
        //get select list index
        int srcIndex = sourceList.getSelectedIndex();
        //get sample at selected list index from linkedlist
        Source src = sources.get(srcIndex);
        openAL.setPitch(src, pitchSlider.getValue());
    }//GEN-LAST:event_pitchSliderStateChanged

    private void deleteSrcButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSrcButActionPerformed
        //get select list index
        int srcIndex = sourceList.getSelectedIndex();
        //get sample at selected list index from linkedlist
        Source src = sources.remove(srcIndex);
        openAL.clearSource(src);
        sourceListModel.remove(srcIndex);
    }//GEN-LAST:event_deleteSrcButActionPerformed

    private void moveSource1ButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveSource1ButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moveSource1ButActionPerformed

    private void moveSource3ButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveSource3ButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moveSource3ButActionPerformed

    private void moveSource5ButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveSource5ButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moveSource5ButActionPerformed

    private void moveListener1ButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveListener1ButActionPerformed
        float[] vel = new float[3];
        String[] s = listenerVelocityInput.getText().split("");
        for (int i = 0; i < s.length; i++)
            vel[i] = Float.parseFloat(s[i]);
        openAL.moveListener(listenerPositionInput, vel, 1);
    }//GEN-LAST:event_moveListener1ButActionPerformed

    private void moveListener3ButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveListener3ButActionPerformed
        float[] vel = new float[3];
        String[] s = listenerVelocityInput.getText().split("");
        for (int i = 0; i < s.length; i++)
            vel[i] = Float.parseFloat(s[i]);
        openAL.moveListener(listenerPositionInput, vel, 3);
    }//GEN-LAST:event_moveListener3ButActionPerformed

    private void moveListener5ButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveListener5ButActionPerformed
        float[] vel = new float[3];
        String[] s = listenerVelocityInput.getText().split("");
        for (int i = 0; i < s.length; i++)
            vel[i] = Float.parseFloat(s[i]);
        openAL.moveListener(listenerPositionInput, vel, 5);
    }//GEN-LAST:event_moveListener5ButActionPerformed

    private void cleanUp(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_cleanUp

    }//GEN-LAST:event_cleanUp

    private void loadSourceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadSourceButtonActionPerformed

        //get select list index
        int bufIndex = bufferList.getSelectedIndex();
        //get sample at selected list index from linkedlist
        Buffer buf = buffers.get(bufIndex);

        //create a source for this buffer
        int index = OpenALFacade.storeSource(buf.buffer);
        Source src = new Source(buf, index);
        //store sample in a linkedlist
        sources.add(src);
        //add name of buffer to source list, allowing user to select it to manipulate
        //its properties
        sourceListModel.addElement(src.name);
    }//GEN-LAST:event_loadSourceButtonActionPerformed

    private void loadBufferButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBufferButtonActionPerformed
        fileChooser.setCurrentDirectory(new File(
                System.getProperty("user.dir") + "/src/music"));
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            System.out.println(file.getName());
            buffers.add(new Buffer(file.getName()));
            bufferListModel.addElement(file.getName());
        }
    }//GEN-LAST:event_loadBufferButtonActionPerformed
    private void lookAndFeel() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                    .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList bufferList;
    private javax.swing.JButton deleteSrcBut;
    private javax.swing.JMenuItem exit;
    private javax.swing.JButton fadeInBut;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JCheckBox isLoopingCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JTextField listenerPositionInput;
    private javax.swing.JTextField listenerVelocityInput;
    private javax.swing.JButton loadBufferButton;
    private javax.swing.JButton loadSourceButton;
    private javax.swing.JButton moveListener1But;
    private javax.swing.JButton moveListener3But;
    private javax.swing.JButton moveListener5But;
    private javax.swing.JButton moveSource1But;
    private javax.swing.JButton moveSource3But;
    private javax.swing.JButton moveSource5But;
    private javax.swing.JButton pauseSample1;
    private javax.swing.JSlider pitchSlider;
    private javax.swing.JButton playSample1;
    private javax.swing.JButton setPositionBut;
    private javax.swing.JButton setPositionBut1;
    private javax.swing.JButton setVelocityBut;
    private javax.swing.JButton setVelocityBut1;
    private javax.swing.JTextField soucePositionInput;
    private javax.swing.JList sourceList;
    private javax.swing.JTextField sourceVelocityInput;
    private javax.swing.JButton stopSample1;
    private javax.swing.JButton stopSample10;
    // End of variables declaration//GEN-END:variables

}
